### ISSUE TITLE
101 codelab: Remove "Spacing is irrelevant" sentance

### ISSUE THREAD

**Issue by illia-bobyr** [google/haskell-trainings#14]
Haskell is actually sensitive to spaces in the `let` binding, so this sentence is confusing.
It is also is unnecessary, as people should probably follow examples, and not address this question until later.
But, we may want to add an examples of a multiple `if`/`then`/`else` expression, to show how to write it over multiple lines into the codelab comments.

**Comment by amalloy** [comment]
#15 changes this language to be weaker, in addition to some other changes.

**Comment by illia-bobyr** [comment]
Resolved by https://github.com/google/haskell-trainings/pull/15
