### ISSUE TITLE
PDFs?

### ISSUE THREAD

**Issue by jabbalaci** [google/haskell-trainings#2]
Why don't you upload the PDFs too? If it's a material from 2016, I don't think it would change much in the future.

**Comment by nicuveo** [comment]
That's a good point... though the point of open-sourcing it was for me to keep working on them after I leave Google / for other members of the Haskell team within Google to maintain and adapt them. I'll get back to you on this!

**Comment by ghuntley** [comment]
https://github.com/hmemcpy/haskell-trainings/releases/tag/1.0 by @hmemcpy

**Comment by ghuntley** [comment]
Thankyou @nicuveo

**Comment by nicuveo** [comment]
Done! Created a 1.0 release, that has zip files with the codelabs, and the PDFs.
